[package]
name = "ocr-lib"
version.workspace = true
edition.workspace = true

[dependencies]
oar-ocr.workspace = true
ort = { version = "=2.0.0-rc.10", default-features = false, features = ["ndarray", "std", "copy-dylibs", "tracing"] }
reqwest.workspace = true
dirs.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
image.workspace = true
